warn user and exit if sources.list not present

diff --git a/ppm b/ppm
--- a/ppm
+++ b/ppm
@@ -369,6 +369,11 @@ remove() {
 }
 
 main() {
+  if [[ ! -f $PPM_SOURCES_FILE ]]; then
+    echo "ERROR: Missing $PPM_SOURCES_FILE"
+    exit 1
+  fi
+
   local command="$1" config=false config_flag="" force=false force_flag=""
   shift
 
